const Queue = require('bee-queue');

module.exports = () => {
	// auto generated by the queue entrypoint
	const { ip: host, port } = require('./config.json');

	return new Queue('chess', { redis: { host, port } });
};
